### ISSUE TITLE
Error when running downstream.py

### ISSUE THREAD

**Issue by MichaelMaiii** [SPOClab-ca/BENDR#13]
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/95026726/161910352-9e24ee1e-7286-48d2-913a-05e9a45ed161.png">
I didn't change the original code, but I got this error. 
The library version has been verified. 
Does anyone know the solution?

**Comment by Vpredictor** [comment]
I have the same problem. Did you solve the problem?

**Comment by jc-audet** [comment]
I have the same problem. Did anyone manage to solve the problem?

**Comment by zhj2020** [comment]
> <img alt="image" width="1229" src="https://user-images.githubusercontent.com/95026726/161910352-9e24ee1e-7286-48d2-913a-05e9a45ed161.png">
> 
> I didn't change the original code, but I got this error. The library version has been verified. Does anyone know the solution?

Have you solved it？

**Comment by Vica75** [comment]
Change **ds.train_params to **ds.train_params._d in the call to provess.fit in downstream.py. Solved the issue for me.
