### ISSUE TITLE
Channel and referencing

### ISSUE THREAD

**Issue by ywatanabe1989** [SPOClab-ca/BENDR#18]
Hi,

I have two questions. Specifically,

1) What is the channel order of the 10-20 system for the model?
2) Also, what is the appropriate referencing method for channels?

Thank you very much for your consideration.

**Comment by ywatanabe1989** [comment]
I'm not sure but deep1010 may map channels for the standard 10-20 system.
https://github.com/SPOClab-ca/dn3/blob/f6c3ddcba2a986c2021dc3efb076b1d1079d7739/dn3/transforms/channels.py

**Comment by kostasde** [comment]
Indeed, if channel labels follow reasonable conventions, channels should be appropriately mapped. There is a lot of log output that should confirm this while you load your data.

I can't recall too much more about it though.

**Comment by kostasde** [comment]
By appropriately mapped, 10-20 channels should consistently go to the indices of the deep1010 that they correspond to.

**Comment by ywatanabe1989** [comment]
Thank you very much.

Unfortunately, I am applying the BENDR model to our own dataset.

Probably, is this the expected channel order?
https://github.com/SPOClab-ca/dn3/blob/master/dn3/transforms/instance.py#L406-412
