### ISSUE TITLE
About deploy downstream.yml and downstream_datasets.yml

### ISSUE THREAD

**Issue by YoloEliwa** [SPOClab-ca/BENDR#6]
Tranks for supplying your code. But when I follow your markdown, I meet some problems
![image](https://user-images.githubusercontent.com/57787767/137582812-6c8fe69b-0371-4a3c-a3ab-428658f3906b.png)

This is my project files
![image](https://user-images.githubusercontent.com/57787767/137582840-aad255ae-219b-4051-97c4-5b3bd4ae04d7.png)

This is my downstream.yml 
![image](https://user-images.githubusercontent.com/57787767/137582893-431f0047-7566-44ac-83b2-3b59dbe406d6.png)

This is my downstream_datasets.yml
![image](https://user-images.githubusercontent.com/57787767/137582906-ab65e001-e6ec-4bdf-a5c5-b916eb8a86ae.png)

**Comment by kostasde** [comment]
It looks like you just accidentally modified the datasets entry in `downstream.yml`, it should be

`datasets: !include configs/downstream_datasets.yml`

If you _only_ want to _use_ `bci_iv_2a`, you should just list that as the single option in the `use_only:` section in `downstream.yml`
